### ISSUE TITLE
Problems with model running and pose ranking

### ISSUE THREAD

**Issue by 2023ComputBio** [Zhang-Runze/PackDock#1]
Dear Sir,

Thank you for open-sourcing this work. After reviewing your preprint article and code, I have some questions and am wondering if you could provide some clarification?
1. I am interested in trying this method for flexible docking, but there are missing parts in the open-sourced code that prevent it from running properly.
2. If your method were usable, how could I select the most likely correct pose out of all the samples? It seems from the examples you provided that there is no confidence score given for selection. 
Similarly, how were the accuracies of side-chain packing and the proportions of ligand RMSD < 2 Å calculated across various benchmarks in the article (such as Fig. 2, Fig. 3, and Table 1)? There is no mention of a confidence model in either the article or your code. Are these metrics calculated by selecting the conformation closest to the ground truth from the sampled conformations?
3. I am very interested in flexible docking, so I am considering how to re-train your model. I am wondering if PackPocket, being trained on the BC40 dataset—a subset of the PDB database for side-chain packing—might have an intersection with the pockets in the PDBbind test set, leading to potential data leakage.

Best,

**Comment by Zhang-Runze** [comment]
Thank you for your attention and questions!

1. We have updated the code, and if you still encounter bugs in the latest version, could you please provide more details? Once again, thank you for your interest in our work!

2. Right, in this work, we have primarily focused on sampling the correct protein-ligand complex conformations. Therefore, for all methods, we mainly analyzed conformations closest to the ground truth. The scoring function is indeed a crucial research direction, as it is not only essential for conformation selection but also for virtual screening. We plan to delve deeper into this area in the future.
Additionally, the current flexible docking can provide a reference pose score (ranking), such as the Vina score. We have also analyzed the performance of the top-1 pose in flexible docking.

3. Thank you for your attention to our work! We have considered the issue of data leakage carefully. Firstly, through statistical analysis, we observed that only a very small number of PDB IDs overlap between the BC40 dataset and the PDBBind test set (approximately 5). Moreover, among these 5 proteins, due to differences in the methods used for pocket extraction, only a small portion of amino acids overlap.
Additionally, we trained two models using separate datasets and tested them separately in packing experiments. In the redocking experiments, we only evaluated side chain conformations or docking poses predicted by the model trained on PDBBind. In other more valuable flexible docking experiments (three types of cross-docking), we predicted holo structures starting from apo (non-homologous holo or AF2) structures. 

Thank you for your question, and if there are additional details that need to be discussed, you can also email me！
